package com.android.zubanx.feature.translate

data class LanguageItem(val code: String, val name: String) {
    companion object {
        val DETECT = LanguageItem("auto", "Detect Language")

        val ALL: List<LanguageItem> = listOf(
            LanguageItem("en", "English"),
            LanguageItem("ur", "Urdu"),
            LanguageItem("hi", "Hindi"),
            LanguageItem("ar", "Arabic"),
            LanguageItem("zh", "Chinese (Simplified)"),
            LanguageItem("zh-TW", "Chinese (Traditional)"),
            LanguageItem("fr", "French"),
            LanguageItem("de", "German"),
            LanguageItem("es", "Spanish"),
            LanguageItem("it", "Italian"),
            LanguageItem("pt", "Portuguese"),
            LanguageItem("ru", "Russian"),
            LanguageItem("ja", "Japanese"),
            LanguageItem("ko", "Korean"),
            LanguageItem("tr", "Turkish"),
            LanguageItem("fa", "Persian"),
            LanguageItem("bn", "Bengali"),
            LanguageItem("pa", "Punjabi"),
            LanguageItem("ms", "Malay"),
            LanguageItem("id", "Indonesian"),
            LanguageItem("nl", "Dutch"),
            LanguageItem("pl", "Polish"),
            LanguageItem("sv", "Swedish"),
            LanguageItem("da", "Danish"),
            LanguageItem("fi", "Finnish"),
            LanguageItem("no", "Norwegian"),
            LanguageItem("cs", "Czech"),
            LanguageItem("ro", "Romanian"),
            LanguageItem("hu", "Hungarian"),
            LanguageItem("vi", "Vietnamese"),
            LanguageItem("th", "Thai"),
            LanguageItem("uk", "Ukrainian"),
            LanguageItem("he", "Hebrew"),
            LanguageItem("sw", "Swahili"),
            LanguageItem("af", "Afrikaans"),
            LanguageItem("sq", "Albanian"),
            LanguageItem("am", "Amharic"),
            LanguageItem("hy", "Armenian"),
            LanguageItem("az", "Azerbaijani"),
            LanguageItem("bs", "Bosnian"),
            LanguageItem("bg", "Bulgarian"),
            LanguageItem("ca", "Catalan"),
            LanguageItem("hr", "Croatian"),
            LanguageItem("et", "Estonian"),
            LanguageItem("ka", "Georgian"),
            LanguageItem("el", "Greek"),
            LanguageItem("gu", "Gujarati"),
            LanguageItem("ht", "Haitian Creole"),
            LanguageItem("ha", "Hausa"),
            LanguageItem("is", "Icelandic"),
            LanguageItem("ig", "Igbo"),
            LanguageItem("jw", "Javanese"),
            LanguageItem("kn", "Kannada"),
            LanguageItem("kk", "Kazakh"),
            LanguageItem("km", "Khmer"),
            LanguageItem("ku", "Kurdish"),
            LanguageItem("ky", "Kyrgyz"),
            LanguageItem("lo", "Lao"),
            LanguageItem("la", "Latin"),
            LanguageItem("lv", "Latvian"),
            LanguageItem("lt", "Lithuanian"),
            LanguageItem("lb", "Luxembourgish"),
            LanguageItem("mk", "Macedonian"),
            LanguageItem("mg", "Malagasy"),
            LanguageItem("ml", "Malayalam"),
            LanguageItem("mt", "Maltese"),
            LanguageItem("mi", "Maori"),
            LanguageItem("mr", "Marathi"),
            LanguageItem("mn", "Mongolian"),
            LanguageItem("my", "Myanmar (Burmese)"),
            LanguageItem("ne", "Nepali"),
            LanguageItem("ny", "Nyanja (Chichewa)"),
            LanguageItem("or", "Odia (Oriya)"),
            LanguageItem("ps", "Pashto"),
            LanguageItem("si", "Sinhala"),
            LanguageItem("sk", "Slovak"),
            LanguageItem("sl", "Slovenian"),
            LanguageItem("so", "Somali"),
            LanguageItem("su", "Sundanese"),
            LanguageItem("tl", "Tagalog (Filipino)"),
            LanguageItem("tg", "Tajik"),
            LanguageItem("ta", "Tamil"),
            LanguageItem("tt", "Tatar"),
            LanguageItem("te", "Telugu"),
            LanguageItem("uz", "Uzbek"),
            LanguageItem("cy", "Welsh"),
            LanguageItem("xh", "Xhosa"),
            LanguageItem("yi", "Yiddish"),
            LanguageItem("yo", "Yoruba"),
            LanguageItem("zu", "Zulu")
        )

        fun fromCode(code: String): LanguageItem =
            ALL.find { it.code == code } ?: LanguageItem(code, code.uppercase())
    }
}
